### ISSUE TITLE
Feature request: direct open of last remaining app

### ISSUE THREAD

**Issue by violoncelloCH** [seizonsenryaku/HayaiLauncher#106]
Option to directly open the last remaining app while searching
Would make the starting process much easier

**Comment by avuton** [comment]
If I understand this correctly, are you saying:

When I search, if there is one application remaining start that application without user interaction.

This seems like it would be unexpected user interface behaviour over user interaction. I think the current user interaction (touch go on the soft keyboard, enter on a hard keyboard, or the touch icon) strikes a better balance and if this feature request was implemented users could easily start applications unexpectedly after a typo, or otherwise.

**Comment by violoncelloCH** [comment]
Oh, it's implemented by pressing enter... Didn't know that... Makes it much easier already to know this...
I understand what you mean
maybe an explanation to press enter to open the remaining app would be nice!
