### ISSUE TITLE
Add no icons mode

### ISSUE THREAD

**Issue by volnes** [seizonsenryaku/HayaiLauncher#44]
For old devices, when launcher restart caching icons loads too long

**Comment by seizonsenryaku** [comment]
There used to be an option to don't load the icons, but I removed it because I didn't find it very useful after I made the icon loading run in separated threads. 
The icon loading should happen in background and should not affect the app too much responsibility (unless you are on a single core CPU maybe). 
Isn't it better to slowly load the icons than not loading them at all?

**Comment by volnes** [comment]
yes i have single core CPU and yes not load icons is better)))

**Comment by IBPX** [comment]
+1. Old devices need all the help they can get.

**Comment by seizonsenryaku** [comment]
Implemented in 1.2.3
